// packages/solid/src/session-context.ts
/**
 * Solid.js session context — createContext/useContext pattern for Session.
 */

import { createContext, useContext, onMount, onCleanup } from 'solid-js';
import { createSession, type Session, type SessionOptions } from '@muix/core';

const SessionContext = createContext<Session | null>(null);

export { SessionContext };

export interface SessionProviderProps {
  children: unknown;
  session?: Session;
  options?: SessionOptions;
}

/**
 * Creates and provides a Session for the component tree.
 * Returns [session, Provider] so callers can use it imperatively or as JSX.
 */
export function createSessionProvider(opts: SessionProviderProps = { children: null }): {
  session: Session;
  Provider: typeof SessionContext.Provider;
} {
  const session = opts.session ?? createSession(opts.options);

  let started = false;

  onMount(async () => {
    await session.start();
    started = true;
  });

  onCleanup(() => {
    if (!opts.session && started) {
      session.terminate('SessionProvider unmounted').catch(() => {});
    }
  });

  return { session, Provider: SessionContext.Provider };
}

export function useSession(): Session {
  const session = useContext(SessionContext);
  if (!session) {
    throw new Error('useSession must be called inside a SessionContext.Provider');
  }
  return session;
}

// packages/react/src/session-context.tsx
/**
 * SessionProvider and useSession — React context for Session lifecycle.
 */

import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useRef,
  type ReactNode,
} from 'react';
import { createSession, type Session, type SessionOptions } from '@muix/core';

interface SessionContextValue {
  session: Session;
}

const SessionContext = createContext<SessionContextValue | null>(null);

export interface SessionProviderProps {
  children: ReactNode;
  /** Provide an existing session, or let the provider create and manage one */
  session?: Session;
  options?: SessionOptions;
}

export function SessionProvider({
  children,
  session: externalSession,
  options,
}: SessionProviderProps): React.ReactElement {
  const sessionRef = useRef<Session | null>(null);

  if (!sessionRef.current) {
    sessionRef.current = externalSession ?? createSession(options);
  }

  const session = sessionRef.current;

  useEffect(() => {
    let started = false;
    session.start().then(() => { started = true; }).catch(() => {});

    return () => {
      // Only terminate sessions we created (not external ones)
      if (!externalSession && started) {
        session.terminate('SessionProvider unmounted').catch(() => {});
      }
    };
  }, [session, externalSession]);

  const value = useMemo(() => ({ session }), [session]);

  return (
    <SessionContext.Provider value={value}>{children}</SessionContext.Provider>
  );
}

export function useSession(): Session {
  const ctx = useContext(SessionContext);
  if (!ctx) {
    throw new Error('useSession must be used within a <SessionProvider>');
  }
  return ctx.session;
}
