// packages/solid/src/use-agent.ts
/**
 * useAgent — Solid.js composable for streaming LLM responses via AgentChannel.
 */

import { createSignal as createSolidSignal, onCleanup } from 'solid-js';
import type { AgentChannel, AgentMessage, AgentStreamFrame } from '@muix/agent';

export interface UseAgentOptions {
  channel: AgentChannel;
}

export interface UseAgentResult {
  send: (message: AgentMessage) => void;
  history: () => AgentMessage[];
  streamingText: () => string;
  isStreaming: () => boolean;
  cancel: () => void;
  clear: () => void;
}

export function useAgent(options: UseAgentOptions): UseAgentResult {
  const { channel } = options;

  const [history, setHistory] = createSolidSignal<AgentMessage[]>([]);
  const [streamingText, setStreamingText] = createSolidSignal('');
  const [isStreaming, setIsStreaming] = createSolidSignal(false);

  let currentAction: { cancel(): void } | null = null;
  let currentSub: { unsubscribe(): void } | null = null;

  const cancel = (): void => {
    currentAction?.cancel();
    currentSub?.unsubscribe();
    currentAction = null;
    currentSub = null;
    setIsStreaming(false);
  };

  const send = (message: AgentMessage): void => {
    cancel();

    setHistory((h) => [...h, message]);
    setStreamingText('');
    setIsStreaming(true);

    const action = channel.sendMessage(message);
    currentAction = action;

    currentSub = channel.observe().subscribe({
      next: (frame) => {
        const f = frame.data as AgentStreamFrame;
        if (f.type === 'delta' && f.content) {
          setStreamingText((t) => t + f.content!);
        }
        if (f.type === 'done' || f.type === 'error') {
          setIsStreaming(false);
          const text = streamingText();
          if (text) {
            setHistory((h) => [...h, { role: 'assistant', content: text }]);
            setStreamingText('');
          }
          currentSub?.unsubscribe();
          currentSub = null;
        }
      },
    });
  };

  const clear = (): void => {
    cancel();
    setHistory([]);
    setStreamingText('');
  };

  onCleanup(() => cancel());

  return { send, history, streamingText, isStreaming, cancel, clear };
}

// packages/react/src/use-agent.ts
/**
 * useAgent — React hook for LLM streaming interactions.
 */

import { useState, useCallback, useRef } from 'react';
import type { AgentChannel, AgentMessage, AgentStreamFrame } from '@muix/agent';

export interface UseAgentOptions {
  channel: AgentChannel;
}

export interface UseAgentResult {
  /** Send a message and start streaming */
  send: (message: AgentMessage) => void;
  /** Accumulated message history */
  history: AgentMessage[];
  /** Streaming frames from the current response */
  streamFrames: AgentStreamFrame[];
  /** Whether the agent is currently streaming */
  isStreaming: boolean;
  /** Text assembled from current stream deltas */
  streamingText: string;
  /** Cancel the current stream */
  cancel: () => void;
  /** Clear history */
  clear: () => void;
  /** Last error, if any */
  error: unknown | null;
}

export function useAgent({ channel }: UseAgentOptions): UseAgentResult {
  const [history, setHistory] = useState<AgentMessage[]>([]);
  const [streamFrames, setStreamFrames] = useState<AgentStreamFrame[]>([]);
  const [streamingText, setStreamingText] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [error, setError] = useState<unknown | null>(null);
  const cancelRef = useRef<(() => void) | null>(null);

  const send = useCallback(
    (message: AgentMessage) => {
      // Cancel any existing stream
      cancelRef.current?.();
      setStreamFrames([]);
      setStreamingText('');
      setError(null);
      setIsStreaming(true);

      setHistory((prev) => [...prev, message]);

      const abortController = new AbortController();
      cancelRef.current = () => abortController.abort();

      const action = channel.sendMessage(message, { signal: abortController.signal });

      let accumulated = '';

      // Observe streaming progress
      const sub = action.observe().subscribe({
        next: (progress) => {
          const partial = progress.partial;
          if (Array.isArray(partial)) {
            setStreamFrames([...partial]);
            // Rebuild streaming text from deltas
            accumulated = partial
              .filter((f: AgentStreamFrame) => f.type === 'delta' && f.content)
              .map((f: AgentStreamFrame) => f.content ?? '')
              .join('');
            setStreamingText(accumulated);
          }
        },
      });

      action.status.observe().subscribe({
        next: (status) => {
          if (status === 'completed') {
            setIsStreaming(false);
            // Update history with assistant response
            if (accumulated) {
              setHistory((prev) => [
                ...prev,
                { role: 'assistant', content: accumulated },
              ]);
            }
            sub.unsubscribe();
          } else if (status === 'failed') {
            setIsStreaming(false);
            setError(action.error.value);
            sub.unsubscribe();
          } else if (status === 'cancelled') {
            setIsStreaming(false);
            sub.unsubscribe();
          }
        },
      });
    },
    [channel],
  );

  const cancel = useCallback(() => {
    cancelRef.current?.();
    setIsStreaming(false);
  }, []);

  const clear = useCallback(() => {
    cancelRef.current?.();
    setHistory([]);
    setStreamFrames([]);
    setStreamingText('');
    setIsStreaming(false);
    setError(null);
    channel.clearHistory();
  }, [channel]);

  return {
    send,
    history,
    streamFrames,
    isStreaming,
    streamingText,
    cancel,
    clear,
    error,
  };
}
